import { spawnSync } from "node:child_process";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";

// vitest runs from the package root; jsdom makes import.meta.url an http URL,
// so resolve the CLI path from cwd instead.
const CLI = resolve(process.cwd(), "bin", "form-render.mjs");

function runCli(cwd: string, args: string[]) {
  return spawnSync(process.execPath, [CLI, ...args], { cwd, encoding: "utf8" });
}

describe("CLI: add shadcn", () => {
  let dir: string;
  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), "fr-cli-"));
  });
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  const adapterPath = () => join(dir, "src", "lib", "form-render-shadcn.tsx");

  it("scaffolds the adapter with a clean header and the expected exports", () => {
    const res = runCli(dir, ["add", "shadcn", "--no-deps"]);
    expect(res.status).toBe(0);

    const file = readFileSync(adapterPath(), "utf8");
    expect(file).not.toContain("@ts-nocheck");
    expect(file).toContain("generated by `form-render add shadcn`");
    expect(file).toContain("export const shadcnComponents");
    expect(file).toContain("export const shadcnSlots");
  });

  it("scaffolds the file-field Dropzone alongside the adapter", () => {
    const res = runCli(dir, ["add", "shadcn", "--no-deps"]);
    expect(res.status).toBe(0);

    const dropzone = readFileSync(join(dir, "src", "components", "ui", "dropzone.tsx"), "utf8");
    expect(dropzone).not.toContain("@ts-nocheck");
    expect(dropzone).toContain("export function Dropzone");
    expect(dropzone).toContain("react-dropzone");
    // the adapter imports it
    expect(readFileSync(adapterPath(), "utf8")).toContain('from "@/components/ui/dropzone"');
  });

  it("refuses to overwrite an existing file without --force", () => {
    runCli(dir, ["add", "shadcn", "--no-deps"]);
    const res = runCli(dir, ["add", "shadcn", "--no-deps"]);
    expect(res.status).toBe(1);
    expect(res.stderr).toMatch(/already exists/);
  });

  it("overwrites with --force", () => {
    runCli(dir, ["add", "shadcn", "--no-deps"]);
    const res = runCli(dir, ["add", "shadcn", "--no-deps", "--force"]);
    expect(res.status).toBe(0);
  });

  it("rewrites imports to match custom components.json aliases", () => {
    writeFileSync(
      join(dir, "components.json"),
      JSON.stringify({ aliases: { ui: "@/ui", utils: "@/lib/cn" } }),
    );
    runCli(dir, ["add", "shadcn", "--no-deps"]);
    const file = readFileSync(adapterPath(), "utf8");
    expect(file).toContain('from "@/ui/button"');
    expect(file).toContain('from "@/lib/cn"');
    expect(file).not.toContain('from "@/components/ui/button"');
  });

  it("warns (does not hang) when shadcn isn't initialized", () => {
    const res = runCli(dir, ["add", "shadcn"]);
    expect(res.status).toBe(0);
    expect(res.stdout).toMatch(/isn't initialized/);
  });

  it("prints help for --help", () => {
    const res = runCli(dir, ["--help"]);
    expect(res.status).toBe(0);
    expect(res.stdout).toMatch(/scaffolding CLI/);
  });
});
